name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: echo "$SSH_KEY" > id_rsa && chmod 400 id_rsa

      - name: SSH Connection and Deploy
        run: |
          ssh -i ./id_rsa ec2-user@44.193.83.68 '
            echo "SSH Connection successful" &&
            docker build -t conversao-temperatura/conversao:1.0 . &&
            docker run -d -p 8080:8080 conversao-temperatura/conversao:1.0
          '
