name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H 44.193.83.68 >> ~/.ssh/known_hosts

      - name: SSH Connection and Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@44.193.83.68 '
            echo "SSH Connection successful" &&
            git clone https://github.com/giovannipajeu1/conversao-temperatura.git &&
            cd conversao-temperatura &&
            docker build -t conversao-temperatura/conversao:1.0 . &&
            docker run -d -p 8080:8080 conversao-temperatura/conversao:1.0
          '
